name: Daily Instagram Post

# Workflow for automated Instagram posting
on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12:00 PM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  post:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create session file
      run: |
        echo '${{ secrets.INSTAGRAM_SESSION }}' > instagram_session.json
    
    - name: Create .env file
      run: |
        echo "INSTAGRAM_USERNAME=${{ secrets.INSTAGRAM_USERNAME }}" >> .env
        echo "INSTAGRAM_PASSWORD=${{ secrets.INSTAGRAM_PASSWORD }}" >> .env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
    
    - name: Run Instagram poster
      id: poster
      run: |
        python instagram_poster.py
        echo "status=success" >> $GITHUB_OUTPUT
      env:
        INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
        INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    - name: Send Notification on Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const run_link = `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`;
          const message = `⚠️ Instagram Auto Poster Failed!\n\nWorkflow: ${context.workflow}\nRun: ${run_link}\nTime: ${new Date().toISOString()}\n\nPlease check the workflow logs and you may need to refresh your Instagram session.`;
          
          await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '❌ Instagram Auto Poster Failed',
            body: message,
            labels: ['automation-error']
          });
    
    - name: Send Success Notification
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const run_link = `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`;
          console.log(`✅ Instagram post successful! Check the run at ${run_link}`); 